//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedia
    {
        public tblMedia()
        {
            this.tblPlaylistMappings = new HashSet<tblPlaylistMapping>();
        }
    
        public int MId { get; set; }
        public string Location { get; set; }
        public string Title { get; set; }
        public Nullable<int> PlayCount { get; set; }
        public string FirstArtist { get; set; }
        public string FirstComposer { get; set; }
        public string FirstGenere { get; set; }
        public string Album { get; set; }
        public string Year { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<decimal> TotalLenghtMins { get; set; }
    
        public virtual ICollection<tblPlaylistMapping> tblPlaylistMappings { get; set; }
    }
}
