//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlaylist
    {
        public tblPlaylist()
        {
            this.tblPlaylistMappings = new HashSet<tblPlaylistMapping>();
        }
    
        public int PId { get; set; }
        public string PlaylistName { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SongCount { get; set; }
    
        public virtual ICollection<tblPlaylistMapping> tblPlaylistMappings { get; set; }
    }
}
